### ISSUE TITLE
[decancer]logic for stripping on autodecancer

### ISSUE THREAD

**Issue by kablekompany** [kablekompany/Kable-Kogs#4]
Currently sanitizing pulls moniker and exchanges characters for utf relative and title cases for aesthetic. This title case needs to be removed so bot will ignore non cancerous new members instead of trying to change their name for proper case.

**Comment by phenom4n4n** [comment]
Titlecasing doesn't seem to be an issue currently. I'm seeing unnecessary decancers like [this one](https://rickroll.click-if-you-da.re/AmOYHE.png) due to the user having spaces in their name, which isn't an alphanumeric character, so it makes it past the alnum check. One way to fix this might be to split the nickname before decancering and then checking each segment against the alnum/ascii check. If none of the segments fail, the bot exits and doesn't decancer the user.
